import '@fontsource-variable/dm-sans/wght.css';
import './styles.css';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import exam from './exam-data.json';
import { formatAnswer as displayAnswer } from './answer-format.js';
import referenceLicense from './reference-license.txt?raw';
import retestBank from './retest-data.json';
import { createSession, recordAnswer, skipQuestion, finishSession, gradeQuestion, getResults, reviewAnswer, revisitQuestion, returnToExam, getProgressCounts } from './exam-engine.js';
import { domainMeta, sourceGroups, coverageNotes, labRecommendations, getStudyPriorities } from './learning-content.js';

const paths = {
 network:'M4 4h6v6H4zM14 14h6v6h-6zM14 4h6v6h-6zM4 14h6v6H4zM10 7h4M7 10v4M17 10v4M10 17h4',
 layers:'m12 3 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5',
 book:'M12 6c-3-3-7-3-9-2v15c3-1 6-1 9 2 3-3 6-3 9-2V4c-3-1-6-1-9 2Zm0 0v15',
 chart:'M4 20V10m8 10V4m8 16v-7',
 chevron:'m9 5 7 7-7 7', arrow:'M4 12h16m-6-6 6 6-6 6', arrowLeft:'M20 12H4m6-6-6 6 6 6',
 check:'m5 12 4 4L19 6', close:'m6 6 12 12M6 18 18 6', clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
 play:'m8 5 11 7-11 7V5Z', pause:'M8 5v14M16 5v14', flag:'M5 21V4m0 0c4-4 8 4 14 0v10c-6 4-10-4-14 0',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Zm-4 9 3 3 5-6',
 info:'M12 11v6m0-10v.1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
 help:'M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4v.1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
 external:'M14 3h7v7m0-7L10 14M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5',
 route:'M6 6h12M6 18h12M6 6v12M18 6v12M9 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm12 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',
 server:'M3 3h18v7H3zM3 14h18v7H3zM7 6.5h.01M7 17.5h.01M12 6.5h5M12 17.5h5',
 code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',
 refresh:'M3 10a9 9 0 1 1 1 7M3 3v7h7', menu:'M4 6h16M4 12h16M4 18h16',
 download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5', spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3',
 terminal:'m5 7 4 5-4 5m8 0h6', target:'M12 8a4 4 0 1 0 4 4M12 3a9 9 0 1 0 9 9M12 12l9-9m-5 0h5v5',
 lock:'M6 10h12v11H6zM8 10V6a4 4 0 0 1 8 0v4', heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8'
};
const icon = (name,cls='') => `<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name] || paths.book}"/></svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const markdown = text => DOMPurify.sanitize(marked.parse(String(text || ''),{breaks:false}));
const safeLink = (url,label) => `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}${icon('external')}</a>`;
const key = 'packetwise.session.v1';
const app = document.querySelector('#app');
let storageAvailable = true;
let data;
try { data=JSON.parse(localStorage.getItem(key)); } catch { storageAvailable=false; }
const fresh = carryOver => ({session:createSession(exam.questions,{carryOver}),kind:'main',retestIds:[],drafts:{},flags:[],timer:{remaining:3600,running:false,deadline:null},feedbackId:null});
if (!data || data.session?.version!==1 || !Array.isArray(data.session?.questionIds)) data=fresh(false);
const ui = {modal:null,toast:'',mobileOpen:false,error:'',reviewFilter:'all',sourceQuery:'',toastTimeout:null};
let modalReturnFocus=null;
function questions(){return data.kind==='retest' ? data.retestIds.map(id=>retestBank.find(q=>q.id===id)).filter(Boolean) : exam.questions;}
function current(){return questions()[data.session.currentIndex];}
function isCli(q){return /cli/i.test(q.format);}
function isOrder(q){return /ordering/i.test(q.format);}
function isMatch(q){return /matching/i.test(q.format);}
function promptHtml(q){return markdown(isMatch(q)?q.prompt.replace(/^([A-Z])\. (.+)$/gm,'- **$1.** $2'):q.prompt);}
function matchingChoices(q){return [...q.prompt.matchAll(/^([A-Z])\. (.+)$/gm)].map(([,letter,label])=>[letter,label.replace(/`/g,'')]);}
function responseFor(q){return data.drafts[q.id] ?? data.session.answers[q.id];}
function replaceAttempt(next){const previous={...data};delete previous.previousAttempt;data={...next,previousAttempt:previous};}
function isMulti(q){return Array.isArray(q.correct_answer)&&!isCli(q)&&!isOrder(q);}
function typeLabel(q){return isCli(q)?'CLI simulation':isOrder(q)?'Put in order':isMatch(q)?'Match the items':isMulti(q)?`Select ${q.correct_answer.length}`:'Select one';}
function persist(){try{localStorage.setItem(key,JSON.stringify(data));}catch{storageAvailable=false;}}
function remaining(){return data.timer.running?Math.max(0,Math.ceil((data.timer.deadline-Date.now())/1000)):data.timer.remaining;}
function timeLabel(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function answeredCount(){return getProgressCounts(data.session).answered;}
function toast(message){ui.toast=message;clearTimeout(ui.toastTimeout);renderToast();ui.toastTimeout=setTimeout(()=>{ui.toast='';renderToast();},3800);}
function renderToast(){let el=document.querySelector('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.innerHTML=ui.toast?`${icon('check')}<span>${esc(ui.toast)}</span>`:'';el.classList.toggle('visible',!!ui.toast);}
function saveAndRender(focus=false){persist();render();if(focus)document.querySelector('#question-title')?.focus();}
function setModal(type,payload={}){modalReturnFocus=document.activeElement;ui.modal={type,...payload};renderModal();requestAnimationFrame(()=>document.querySelector('.modal [autofocus], .modal button, .modal a, .modal input')?.focus());}
function closeModal(){ui.modal=null;renderModal();modalReturnFocus?.focus?.();}

function sidebar(){return `<aside class="sidebar ${ui.mobileOpen?'mobile-open':''}" aria-label="Main navigation">
  <a class="brand" href="#" data-action="home" aria-label="PacketWise home"><span class="brand-mark">${icon('network')}</span><span class="brand-name">Packet<span>Wise</span><small class="brand-tag">YOUR NEXT CONNECTION</small></span></a>
  <div class="nav-section-label">WORKSPACE</div>
  <nav>
    <button class="nav-item ${data.session.status!=='finished'?'active':''}" data-action="home">${icon('layers','nav-icon')}<span>Practice exam</span><span class="nav-pill">${questions().length}</span></button>
    <button class="nav-item" data-action="sources">${icon('book','nav-icon')}<span>Study library</span>${icon('external','nav-end')}</button>
    <button class="nav-item ${data.session.status==='finished'?'active':''}" data-action="progress">${icon('chart','nav-icon')}<span>My progress</span></button>
    ${data.previousAttempt?`<button class="nav-item" data-action="restore">${icon('refresh')}<span>Restore previous attempt</span></button>`:''}
  </nav>
  <div class="sidebar-section"><div class="nav-section-label">YOUR PATH</div><div class="path-item"><span class="path-dot"></span><span>CCNA 200-301<small>Network engineering starts here</small></span></div></div>
  <div class="sidebar-bottom"><div class="sidebar-tip"><div class="sidebar-tip-art" aria-hidden="true"><span>${icon('server')}</span><i></i><span>${icon('network')}</span><i></i><span>${icon('code')}</span></div><strong>Small steps. Strong networks.</strong><p>Every question is a connection to your next role.</p><button data-action="guide">How practice works ${icon('arrow')}</button></div>
  <button class="nav-item help-nav" data-action="guide">${icon('help')}<span>Exam guide</span></button>
  <div class="user-profile"><span class="avatar">YOU</span><div><span class="user-name">Future network engineer</span><span class="user-role">Your personal workspace</span></div><span class="online-dot" title="Local workspace"></span></div></div>
</aside>`;}
function topbar(){return `<header class="topbar"><div class="breadcrumbs"><button class="icon-button mobile-menu" data-action="menu" aria-label="Open navigation">${icon('menu')}</button><span>Workspace</span>${icon('chevron')}<strong>${data.session.status==='finished'?'Your review':data.kind==='retest'?'Focused retest':'Practice exam'}</strong></div><div class="topbar-actions"><span class="save-status">${icon(storageAvailable?'check':'info')}<span>${storageAvailable?'Saved on this device':'Progress in this tab'}</span></span><button class="icon-button" data-action="guide" aria-label="Practice exam help">${icon('help')}</button><span class="topbar-avatar" aria-label="Your workspace">Y</span></div></header>`;}
function heading(){return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span> A LITTLE PRACTICE. A LOT OF PROGRESS.</div><h1>${data.kind==='retest'?'Your focused retest':'CCNA practice exam'}<span class="heading-dot">.</span></h1><p>Think it through. Build your confidence. Make the next connection.</p></div><div class="page-heading-actions"><div class="timer-widget ${data.timer.running?'running':''}">${icon('clock')}<div><strong id="timer-clock" class="timer-clock">${timeLabel(remaining())}</strong><span class="timer-label">${data.timer.running?'Practice time left':'Optional practice timer'}</span></div><button class="timer-toggle" data-action="timer" aria-label="${data.timer.running?'Pause':'Start'} timer">${icon(data.timer.running?'pause':'play')}</button></div></div></div>`;}
function modeSwitch(){return `<div class="mode-switch" role="group" aria-label="Feedback mode"><button data-action="mode-exam" class="${data.session.mode==='exam'?'active':''}" aria-pressed="${data.session.mode==='exam'}">${icon('lock')}Exam mode</button><button data-action="mode-study" class="${data.session.mode==='study'?'active':''}" aria-pressed="${data.session.mode==='study'}">${icon('book')}Study mode</button></div>`;}
function inputArea(q){const draft=responseFor(q);
 if(isCli(q))return `<div class="cli-editor"><div class="terminal-header">${icon('terminal')}<span>IOS command workspace</span><span class="simulation-label">TEXT SIMULATION</span></div><label class="sr-only" for="cli-answer">Your Cisco IOS commands</label><textarea id="cli-answer" data-response="cli" spellcheck="false" autocapitalize="off" autocomplete="off" rows="9" placeholder="Enter your configuration commands here…">${esc(draft||'')}</textarea><div class="terminal-footer">Valid IOS abbreviations are accepted. ${icon('code')}</div></div>`;
 if(isMatch(q)){return `<div class="matching-inputs">${Object.keys(q.correct_answer).map(n=>`<div class="matching-row"><label for="match-${n}">Item ${esc(n)}</label>${icon('arrow')}<select id="match-${n}" data-response="match" data-item="${esc(n)}"><option value="">Choose a match</option>${matchingChoices(q).map(([v,label])=>`<option value="${v}" ${draft?.[n]===v?'selected':''}>${v}. ${esc(label)}</option>`).join('')}</select></div>`).join('')}</div>`;}
 if(isOrder(q)){return `<div class="ordering-inputs">${q.correct_answer.map((_,i)=>`<div class="matching-row"><label for="order-${i}"><span class="order-number">${i+1}</span>${['First','Second','Third','Fourth'][i]||'Next'}</label><select id="order-${i}" data-response="order" data-item="${i}"><option value="">Choose a message</option>${Object.entries(q.options).map(([letter,value])=>`<option value="${letter}" ${draft?.[i]===letter?'selected':''}>${letter}. ${esc(value)}</option>`).join('')}</select></div>`).join('')}</div>`;}
 return `<fieldset class="question-options"><legend class="sr-only">${esc(typeLabel(q))}</legend>${Object.entries(q.options||{}).map(([letter,value])=>{const selected=isMulti(q)?(draft||[]).includes(letter):draft===letter;return `<label class="answer-option ${selected?'selected':''}"><input type="${isMulti(q)?'checkbox':'radio'}" name="answer" value="${letter}" data-response="choice" ${selected?'checked':''}/><span class="option-letter">${letter}</span><span class="option-text">${esc(value)}</span><span class="option-indicator">${selected?icon('check'):''}</span></label>`;}).join('')}</fieldset>`;
}
function questionCard(q){return `<section class="question-card" aria-label="Current question"><div class="question-header"><div class="question-progress"><span class="question-kicker">QUESTION ${String(data.session.currentIndex+1).padStart(2,'0')} <span>OF ${questions().length}</span></span><span class="question-type">${esc(typeLabel(q))}</span></div><div class="question-tools"><button class="icon-button ${data.flags.includes(q.id)?'is-flagged':''}" data-action="flag" title="Flag for review" aria-label="${data.flags.includes(q.id)?'Remove flag':'Flag question for review'}" aria-pressed="${data.flags.includes(q.id)}">${icon('flag')}</button><button class="icon-button" data-action="clarify" title="Response instructions" aria-label="Clarify response instructions">${icon('help')}</button></div></div><div class="question-body">${data.session.resumeIndex!=null?'<p class="revisit-note">Reviewing a previous question. Submit to save any answer changes.</p>':''}<h2 id="question-title" class="sr-only" tabindex="-1">Question ${data.session.currentIndex+1} of ${questions().length}</h2><div class="question-prompt">${promptHtml(q)}</div>${inputArea(q)}<p id="answer-error" class="answer-error" role="alert">${esc(ui.error)}</p><div class="answer-hint">${icon(isCli(q)?'terminal':'info')}<span>${isCli(q)?'A configuration exercise, without the hardware.':isMulti(q)?`Choose exactly ${q.correct_answer.length} answers. No partial credit.`:isOrder(q)?'Use each message once, from first to last.':isMatch(q)?'Complete every match before submitting.':'Take your time. Choose the best answer.'}</span></div></div><div class="question-footer"><button class="ghost-button" data-action="${data.session.resumeIndex!=null?'return-to-exam':'skip'}">${data.session.resumeIndex!=null?'Back to exam':'Skip for now'} ${icon('chevron')}</button><button class="primary-button" data-action="submit">${Object.hasOwn(data.session.answers,q.id)?'Save answer':'Submit answer'} ${icon('arrow')}</button></div></section>`;}
function overview(){const count=answeredCount(),all=questions();return `<section class="overview-card"><div class="card-heading"><h2>Your progress</h2><span class="overview-count">${count}<span> / ${all.length}</span></span></div><div class="progress-track" role="progressbar" aria-label="Questions answered" aria-valuemin="0" aria-valuemax="${all.length}" aria-valuenow="${count}"><div class="progress-fill" style="width:${count/all.length*100}%"></div></div><div class="progress-caption"><span>${Math.round(count/all.length*100)}% answered</span><span>${all.length-count} unanswered</span></div><div class="question-grid" aria-label="Question navigator">${all.map((q,i)=>{const a=Object.hasOwn(data.session.answers,q.id),skip=data.session.skippedIds.includes(q.id),active=i===data.session.currentIndex;return `<button class="question-dot ${a?'answered':''} ${active?'current':''} ${skip?'skipped':''} ${data.flags.includes(q.id)?'flagged':''}" data-action="view-question" data-id="${q.id}" ${!data.session.viewedIds.includes(q.id)?'disabled':''} ${active?'aria-current="step"':''} aria-label="Question ${i+1}, ${active?'current':a?'answered':skip?'skipped':data.session.viewedIds.includes(q.id)?'unanswered':'not presented'}${data.flags.includes(q.id)?', flagged':''}">${i+1}${data.flags.includes(q.id)?'<i></i>':''}</button>`;}).join('')}</div><div class="legend"><span><i class="legend-dot answered"></i>Answered</span><span><i class="legend-dot current"></i>Current</span><span><i class="legend-dot skipped"></i>Skipped</span><span><i class="legend-dot flagged"></i>Flagged</span><span><i class="legend-dot"></i>Upcoming</span></div><div class="overview-footer"><div class="review-shortcuts"><button data-action="review-skipped">${data.session.skippedIds.length} skipped ${icon('chevron')}</button><button data-action="review-flags">${icon('flag')}${data.flags.length} flagged ${icon('chevron')}</button></div><button data-action="finish">Finish exam ${icon('arrow')}</button><button class="restart-link" data-action="restart">${icon('refresh')}Start fresh</button></div></section>`;}
function sourceCard(){return `<section class="source-card"><div class="source-icon">${icon('book')}</div><span class="eyebrow">REFERENCES</span><h3>Practice with a purpose.</h3><p>Original networking questions with study notes and labs for further reading.</p><button class="source-link" data-action="sources">Explore the references ${icon('arrow')}</button><div class="source-credit"><span>Independent practice tool<small>Not affiliated with or endorsed by Cisco or Packt.</small></span></div></section>`;}
function practice(){const q=current();if(!q)return reviewCheckpoint();return `${heading()}<div class="workspace-toolbar">${modeSwitch()}<span class="mode-note">${icon(data.session.mode==='exam'?'lock':'spark')}${data.session.mode==='exam'?'Feedback stays hidden until you finish.':'Learn as you go with immediate feedback.'}</span></div><div class="workspace"><div class="question-column">${questionCard(q)}<div class="bottom-note">${icon('shield')}<span>Your next role starts with what you learn today.</span><button data-action="guide">Exam guide</button></div></div><aside class="exam-aside" aria-label="Exam overview">${overview()}${sourceCard()}</aside></div><div class="source-strip"><span>${icon('check')}Original questions</span><i></i><span>${icon('terminal')}Practical IOS simulations</span><i></i><button data-action="sources">${icon('book')}Sources you can trace</button></div>`;}
function reviewCheckpoint(){return `${heading()}<div class="workspace"><section class="question-card checkpoint"><span class="eyebrow">BEFORE YOU FINISH</span><h2 id="question-title" tabindex="-1">A moment to check your answers.</h2><p>You’ve reached the end of the question plan. You can revisit any question you’ve seen, then finish when you’re ready for your results.</p><div class="progress-stats"><div><strong>${answeredCount()} / ${questions().length}</strong><span>Answered</span></div><div><strong>${data.session.skippedIds.length}</strong><span>Skipped</span></div><div><strong>${data.flags.length}</strong><span>Flagged</span></div></div><div class="checkpoint-actions"><button class="secondary-button" data-action="review-skipped">Revisit skipped</button><button class="secondary-button" data-action="review-flags">Review flagged</button></div><p class="small-note">Only submitted answers count. Correctness stays hidden in exam mode until you choose Finish exam.</p><button class="primary-button" data-action="finish">Finish exam ${icon('arrow')}</button></section><aside class="exam-aside" aria-label="Exam overview">${overview()}</aside></div>`;}
function openQuestion(id){const next=revisitQuestion(data.session,id);if(next===data.session){document.querySelector('#question-title')?.focus();return;}data.session=next;ui.modal=null;ui.error='';saveAndRender(true);document.querySelector('.question-card')?.scrollIntoView({behavior:'smooth',block:'start'});}
function questionList(filter){const ids=filter==='skipped'?data.session.skippedIds:data.flags;const rows=questions().map((q,i)=>({q,i})).filter(({q})=>ids.includes(q.id)&&data.session.viewedIds.includes(q.id));return `<p>Choose a question to revisit. Your answers and drafts stay saved while you move between questions.</p><div class="revisit-list">${rows.map(({q,i})=>`<button class="revisit-item" data-action="view-question" data-id="${q.id}"><strong>Question ${i+1}</strong><span>${Object.hasOwn(data.session.answers,q.id)?'Answered':data.session.skippedIds.includes(q.id)?'Skipped':'Unanswered'}${data.flags.includes(q.id)?' · Flagged':''}</span>${icon('chevron')}</button>`).join('')||`<p class="empty-state">No ${filter==='skipped'?'skipped':'flagged'} questions yet.</p>`}</div>`;}

function rubricHtml(q){if(!q.rubric)return '';if(typeof q.rubric==='string')return `<p>${esc(q.rubric)}</p>`;return Object.entries(q.rubric).map(([k,v])=>`<div class="rubric-group"><strong>${esc(k.replaceAll('_',' '))}</strong>${Array.isArray(v)?`<ul>${v.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p>${esc(v)}</p>`}</div>`).join('');}
function explanationHtml(q){return `<div class="review-explanation">${markdown(q.explanation)}</div>${Object.keys(q.distractor_explanations||{}).length?`<div class="distractor-list"><h4>Why the other options don't fit</h4>${Object.entries(q.distractor_explanations).map(([letter,text])=>`<p><strong>${letter}.</strong> ${esc(text)}</p>`).join('')}</div>`:''}${isCli(q)?`<details class="rubric-details"><summary>Accepted commands and grading criteria</summary>${rubricHtml(q)}</details>`:''}<div class="review-sources"><h4>${icon('book')} Supporting material</h4>${q.source_links.map((url,i)=>safeLink(url,q.sources[i].split('/').pop().replace(/\.pdf$/,''))).join('')}<p>${esc(q.source_sections.join(' · '))}</p></div>`;}
function statusName(status){return ({correct:'Correct',incorrect:'Needs practice',skipped:'Skipped',unanswered:'Unanswered',unpresented:'Not presented','needs-review':'CLI review needed'})[status]||status;}
function resolvedResults(){const results=getResults(questions(),data.session);return results;}
function topicRows(results){return results.topics.map(t=>({domain:t.topic,attempted:t.attempted,correct:t.correct,accuracy:t.accuracy,needsReview:t.needsReview}));}
function priorityRows(results){return topicRows(results).map(t=>({...t,attempted:t.attempted-t.needsReview}));}
function reviewItem(row,index){const q=row.question;return `<details class="review-item" data-status="${row.status}"><summary><span class="review-number">${index+1}</span><span class="review-title">${esc(q.topic)}<small>${esc(q.domain)}</small></span><span class="status-pill ${row.status}">${statusName(row.status)}</span>${icon('chevron')}</summary><div class="review-item-body"><div class="review-question">${promptHtml(q)}${q.options&&!isOrder(q)?`<ol class="review-options" type="A">${Object.entries(q.options).map(([l,t])=>`<li><strong>${l}</strong> ${esc(t)}</li>`).join('')}</ol>`:''}</div><div class="answer-comparison"><div><span>Your answer</span><pre>${esc(displayAnswer(q,row.answer))}</pre></div><div><span>Correct answer</span><pre>${esc(displayAnswer(q,q.correct_answer))}</pre></div></div>${row.selfAssessed?'<p class="small-note">CLI outcome confirmed by your own rubric assessment.</p>':''}${row.status==='needs-review'?`<div class="review-callout">${icon('info')}<div><strong>This CLI response needs a human check.</strong><p>The checker could not confidently interpret every command. Compare your final configuration with the required outcomes below; valid equivalent commands count.</p><div class="button-row"><button class="secondary-button" data-action="assess-cli" data-id="${q.id}" data-correct="true">All outcomes satisfied</button><button class="ghost-button" data-action="assess-cli" data-id="${q.id}" data-correct="false">Needs correction</button></div></div></div>`:''}${explanationHtml(q)}</div></details>`;}
function resultsView(){const r=resolvedResults(),topics=topicRows(r),priorities=getStudyPriorities(priorityRows(r)),weak=priorities.map(p=>p.domain),labs=[...labRecommendations].sort((a,b)=>weak.indexOf(b.domain)-weak.indexOf(a.domain));const chosen=[];for(const domain of weak){const lab=labRecommendations.find(l=>l.domain===domain);if(lab&&!chosen.some(l=>l.id===lab.id))chosen.push(lab);}for(const lab of labs){if(chosen.length>=3)break;if(!chosen.some(l=>l.id===lab.id))chosen.push(lab);}const allReview=r.questions;return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span> EVERY ATTEMPT IS A STEP FORWARD</div><h1>Your practice review<span class="heading-dot">.</span></h1><p>A clearer picture of what you know, and where to go next.</p></div><button class="secondary-button" data-action="download">${icon('download')}Export review</button></div>
<section class="results-hero"><div><span class="eyebrow">${r.provisional?'PROVISIONAL PRACTICE SCORE':'YOUR PRACTICE SCORE'}</span><div class="big-score">${r.score}<span> / ${r.total}</span></div><p>${r.provisional?`${r.needsReview} CLI response${r.needsReview===1?' needs':'s need'} a rubric check below.`:'One point for every correct answer. Every question counts equally.'}</p></div><div class="score-circle" style="--score:${r.percentage}%"><span>${Math.round(r.percentage)}<small>% of full exam</small></span></div><div class="results-hero-note">${icon('target')}<strong>${r.accuracy==null?'No answers yet':`${Math.round(r.accuracy)}% attempted accuracy`}</strong><p>${r.attempted} of ${r.total} questions attempted${r.selfAssessed?` · ${r.selfAssessed} self-assessed`:''}${r.provisional?' · accuracy is provisional until manual CLI reviews are resolved':''}.<br>This is practice feedback, not an official passing score.</p></div></section>
<div class="stat-grid">${[['Correct',r.correct,'check'],['Incorrect',r.incorrect,'close'],['Skipped',r.skipped,'chevron'],['Unanswered',r.unanswered,'help'],['Not presented',r.unpresented,'book'],['Awaiting CLI review',r.needsReview,'terminal']].map(([label,n,i])=>`<div class="stat-card">${icon(i)}<strong>${n}</strong><span>${label}</span></div>`).join('')}</div><p class="cli-attempt-summary"><strong>CLI questions attempted: ${r.cliAttempted}</strong> · Awaiting manual review: ${r.needsReview}. CLI attempts are included in your answered total.</p>
<section class="results-section"><div class="section-heading"><div><span class="eyebrow">THE BIGGER PICTURE</span><h2>Performance by topic</h2></div><button class="text-button" data-action="sources">View source coverage ${icon('external')}</button></div><div class="table-scroll"><table class="topic-table"><thead><tr><th>Topic</th><th>Attempted</th><th>Correct</th><th>Accuracy</th><th>Supporting sections</th></tr></thead><tbody>${topics.map(t=>{const meta=domainMeta.find(d=>d.domain===t.domain);const sectionIds=[...new Set(questions().filter(q=>q.domain===t.domain).flatMap(q=>q.sources.map(s=>s.split('/').pop().match(/^\d+(?:-\d+)?/)?.[0]).filter(Boolean)))];return `<tr><td><span class="topic-icon">${icon(meta?.icon)}</span>${esc(meta?.title||t.domain)}</td><td>${t.attempted}</td><td>${t.correct}</td><td><span class="accuracy-cell">${t.accuracy==null?'—':`${Math.round(t.accuracy)}%`}<i><b style="width:${t.accuracy||0}%"></b></i></span></td><td class="supporting-sections">${esc(sectionIds.join(', '))}</td></tr>`;}).join('')}</tbody></table></div><p class="small-note">Small samples are signals for your next practice session, not proof of mastery.</p></section>
<section class="results-section"><div class="section-heading"><div><span class="eyebrow">YOUR NEXT CONNECTIONS</span><h2>Three study priorities</h2></div></div><div class="priority-grid">${priorities.map((p,i)=>`<article class="priority-card"><span class="priority-number">0${i+1}</span><h3>${esc(p.title||p.domain)}</h3><p>${esc(p.reason||p.recommendation||p.message||'Review the referenced sections and test your understanding with another example.')}</p><small>${esc(p.caution||p.sampleNote||'Treat this sample as a starting point, not a mastery judgment.')}</small>${safeLink(questions().find(q=>q.domain===p.domain)?.source_links[0]||sourceGroups[0].links[0].url,'Review the supporting notes')}</article>`).join('')}</div></section>
<section class="results-section"><div class="section-heading"><div><span class="eyebrow">FROM KNOWING TO DOING</span><h2>Take it into the lab</h2></div></div><div class="lab-grid">${chosen.slice(0,3).map(l=>`<article class="lab-card"><span class="lab-badge">${l.original?'ORIGINAL PRACTICE LAB':'RESOURCE LAB'}</span><h3>${esc(l.title)}</h3><ol>${l.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${safeLink(l.sourceUrl,l.sourceSection||'Open the supporting lab')}</article>`).join('')}</div></section>
<section class="results-section"><div class="section-heading"><div><span class="eyebrow">UNDERSTAND EVERY ANSWER</span><h2>Question-by-question review</h2></div><label class="review-filter-label">Show <select id="review-filter"><option value="all" ${ui.reviewFilter==='all'?'selected':''}>All questions</option><option value="practice" ${ui.reviewFilter==='practice'?'selected':''}>Incorrect & unanswered</option><option value="flagged" ${ui.reviewFilter==='flagged'?'selected':''}>Flagged questions</option></select></label></div><div class="review-list">${allReview.map((row,i)=>({row,i})).filter(({row})=>ui.reviewFilter==='all'||ui.reviewFilter==='practice'&&row.status!=='correct'||ui.reviewFilter==='flagged'&&data.flags.includes(row.question.id)).map(({row,i})=>reviewItem(row,i)).join('')||'<div class="empty-state">No questions in this view.</div>'}</div></section>
<section class="coverage-card"><div>${icon('info')}</div><div><h3>What this practice covered</h3><p>The ${r.total}-question ${data.kind==='retest'?'retest':'exam'} covers selected topics from the references. It does not cover the entire resource or establish current Cisco blueprint alignment. Untested topics include broader Syslog/SNMP, wireless security and channels, DHCP snooping, and AI notes. QoS, WAN, cloud and NTP were not used for this exam.</p><button class="text-button" data-action="sources">Read the full coverage notes ${icon('arrow')}</button></div></section>
<section class="retest-card"><div><span class="eyebrow">KEEP THE MOMENTUM</span><h2>${data.kind==='main'?'A fresh start, focused on you.':'Keep building on what you know.'}</h2><p>${data.kind==='main'?'10 original questions, selected around the topics that need more practice.':'Take your next step with the referenced notes and hands-on lab instructions.'}</p></div>${data.kind==='main'?`<button class="primary-button" data-action="retest">Start focused retest ${icon('arrow')}</button>`:`<button class="primary-button" data-action="sources">Continue in the study library ${icon('arrow')}</button>`}</section><div class="results-bottom"><button class="ghost-button" data-action="restart">${icon('refresh')}Restart the full exam</button><span>No official pass mark. No readiness guarantees. Just useful practice.</span></div>`;}
function render(){app.innerHTML=`<div class="app-shell">${sidebar()}<div class="main-shell">${topbar()}<main class="main-content" id="main-content">${data.session.status==='finished'?resultsView():practice()}</main><footer class="site-footer"><span>PacketWise <span>·</span> Learn the connection.</span><button data-action="sources">References & coverage</button></footer></div>${ui.mobileOpen?'<button class="sidebar-overlay" data-action="menu" aria-label="Close navigation"></button>':''}</div><div id="modal-root"></div><div class="sr-only" role="status" id="live-status"></div>`;renderModal();renderToast();}
function announce(text){document.querySelector('#live-status').textContent=text;}

function sourcesModal(){return `<p class="modal-intro">PacketWise is an independent practice tool with original questions based on selected study material. References link to the Cisco CCNA resource repository published by Packt. PacketWise is not affiliated with or endorsed by Cisco or Packt.</p><div class="source-summary"><span>${icon('book')}62 selected PDF files</span><span>${icon('layers')}11 complete Anki text notes</span><span>${icon('check')}Original question set</span></div>${sourceGroups.map(g=>`<details class="source-group"><summary><span>${esc(g.title)}</span>${icon('chevron')}</summary><div><p>${esc(Array.isArray(g.topics)?g.topics.join(' · '):g.topics)}</p><p class="small-note">${esc(Array.isArray(g.sections)?g.sections.join(', '):g.sections)}</p><div class="source-list">${g.links.map(l=>safeLink(l.url,l.label)).join('')}</div></div></details>`).join('')}<div class="coverage-notes"><h3>What we could and couldn't verify</h3><ul>${coverageNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div><details class="reference-license"><summary>Reference license and attribution</summary><p>The referenced repository includes an MIT license, copyright © 2020 Packt. The license notice is retained below. This attribution does not imply a partnership or endorsement. Individual materials may carry separate notices.</p>${safeLink(`https://github.com/${exam.repository}/blob/${exam.commit}/LICENSE`,'View repository license')}<pre>${esc(referenceLicense)}</pre></details><div class="source-version">Reference version <code>${exam.commit.slice(0,12)}</code> ${safeLink(`https://github.com/${exam.repository}/tree/${exam.commit}`,'Open repository')}</div>`;}
function guideModal(){return `<div class="guide-callout">${icon('target')}<div><strong>Practice that makes the next step clearer.</strong><p>Work through a fixed question plan, then turn your results into a study plan.</p></div></div><div class="guide-grid"><div><strong>30 questions · 60 minutes</strong><p>The timer is optional. Start or pause it whenever you need. It will never submit an exam automatically.</p></div><div><strong>One question. One point.</strong><p>Multiple-answer, matching, and ordering questions are all-or-nothing. Equivalent valid IOS commands count.</p></div><div><strong>Exam mode</strong><p>Answers are recorded without hints or correctness. Finish whenever you want to see your review.</p></div><div><strong>Study mode</strong><p>Switch at any point for immediate feedback on the current question and the questions that follow.</p></div></div><h3>Your controls</h3><ul class="guide-controls"><li><strong>Flag</strong><span>Mark a question, then use the flagged list to revisit it before finishing.</span></li><li><strong>Skip for now</strong><span>Leave a question unanswered and move forward. Use the skipped list to return later.</span></li><li><strong>Progress grid</strong><span>Reopen any question you have seen. Submit to save a changed answer, or choose Back to exam to return to your place.</span></li><li><strong>Finish exam</strong><span>End early. Skipped, current unanswered, and unpresented questions stay separate.</span></li><li><strong>Start fresh</strong><span>Start at Question 1. Your previous attempt stays available to restore from the sidebar.</span></li><li><strong>Ctrl / ⌘ + Enter</strong><span>Submit the current response.</span></li></ul><p class="small-note">CLI exercises are text simulations, not device execution. The checker handles common valid IOS equivalents. If it cannot interpret a command confidently, your final review provides the rubric for a manual check.</p><p class="small-note">Your answers are stored in this browser, with no account or cloud sync. You can export your completed review before restarting.</p>`;}
function modalContent(m){const counts=getProgressCounts(data.session);const q=m.id?questions().find(q=>q.id===Number(m.id)):current();switch(m.type){
case 'sources':return {title:'References & study library',subtitle:'FURTHER READING',body:sourcesModal(),wide:true};
case 'guide':return {title:'Make practice work for you',subtitle:'THE EXAM GUIDE',body:guideModal(),wide:true};
case 'progress':return {title:'A look at your progress',subtitle:'NO ANSWERS REVEALED',body:`<div class="progress-stats"><div><strong>${answeredCount()}</strong><span>Answered</span></div><div><strong>${questions().length-answeredCount()}</strong><span>Unanswered</span></div></div><p>${data.session.skippedIds.length} skipped · ${questions().length-data.session.viewedIds.length} not presented · ${data.flags.length} flagged.</p><p>${current()?`You're on question ${data.session.currentIndex+1} of ${questions().length}.`:'You have reached the review checkpoint.'} Correctness remains hidden in exam mode.</p><div class="checkpoint-actions"><button class="secondary-button" data-action="review-skipped">Revisit skipped</button><button class="secondary-button" data-action="review-flags">Review flagged</button></div>`};
case 'question-list':return {title:m.filter==='skipped'?'Revisit skipped questions':'Review flagged questions',subtitle:data.session.mode==='study'?'STUDY MODE · FEEDBACK AFTER SUBMISSION':'EXAM MODE · CORRECTNESS HIDDEN',body:questionList(m.filter)};
case 'clarify':return {title:'Response instructions',subtitle:`QUESTION ${data.session.currentIndex+1}`,body:`<p>${isCli(q)?'Enter the Cisco IOS commands needed to satisfy every stated outcome. Begin in the prompt mode named in the question. Commands are evaluated as text; no device is running.':isMatch(q)?'Choose a letter for each numbered item. Every item must be matched.':isOrder(q)?'Place the listed messages in transmission order, from earliest to latest. Choose each message exactly once.':isMulti(q)?`Choose exactly ${q.correct_answer.length} options. The answer earns a point only if the entire selection is correct.`:'Choose one option. The question contains the assumptions needed to decide.'}</p><p>No topic-specific hints are shown in exam mode.</p><button class="secondary-button" data-action="repeat">${icon('refresh')}Return to the full question</button>`};
case 'recorded':return {title:`Question ${questions().findIndex(x=>x.id===q.id)+1}`,subtitle:'YOUR RECORDED RESPONSE',body:`<div class="recorded-question">${promptHtml(q)}</div><div class="recorded-answer"><span>Your answer</span><pre>${esc(displayAnswer(q,data.session.answers[q.id]))}</pre></div><p class="small-note">The answer key and explanation will appear in your final review.</p>`};
case 'finish':return {title:'Ready to see your review?',subtitle:'FINISH THIS PRACTICE SESSION',body:`<p>You’ve answered <strong>${answeredCount()} of ${questions().length}</strong> questions.</p><p>Your review will separate correct, incorrect, unanswered, skipped and not-presented questions, with explanations and reference links.</p><p class="finish-counts">${counts.answered} answered · ${counts.unanswered} unanswered · ${counts.skipped} skipped · ${counts.unpresented} not presented. Total: ${questions().length}.</p><p>${data.flags.length} flagged for review (flags overlap the counts above).</p><div class="checkpoint-actions"><button class="secondary-button" data-action="review-skipped">Revisit skipped</button><button class="secondary-button" data-action="review-flags">Review flagged</button></div><p class="small-note">Only submitted answers count. Finishing locks this attempt and reveals the answer key.</p>`,footer:`<button class="secondary-button" data-action="close-modal">Keep practicing</button><button class="primary-button" data-action="confirm-finish">Finish & review ${icon('arrow')}</button>`};
case 'restart':return {title:'Start a fresh exam?',subtitle:'RESET THIS BROWSER SESSION',body:'<p>This starts the original 30-question exam at Question 1 with no recorded answers. Your current attempt will be kept as a backup in this browser session.</p><p>You can restore it from the sidebar. Only the most recent previous attempt is kept. This uses the same question set.</p>',footer:'<button class="secondary-button" data-action="close-modal">Keep this session</button><button class="primary-button" data-action="confirm-restart">Start fresh</button>'};
case 'restore':return {title:'Restore your previous attempt?',subtitle:'RETURN TO WHERE YOU LEFT OFF',body:'<p>Your current and previous attempts will swap places, so you can return to either one from the sidebar.</p>',footer:'<button class="secondary-button" data-action="close-modal">Keep this attempt</button><button class="primary-button" data-action="confirm-restore">Restore attempt</button>'};
case 'retest':return {title:'A focused 10-question retest',subtitle:'NEW QUESTIONS. THE SAME MOMENTUM.',body:'<p>We’ll select fresh questions from your three priority areas, then fill any remaining places from the other topics covered by the references.</p><p>The new session uses the same scoring rules and a 20-minute optional timer. Your current review is downloaded before the retest starts.</p>',footer:'<button class="secondary-button" data-action="close-modal">Not yet</button><button class="primary-button" data-action="confirm-retest">Start my retest</button>'};
case 'feedback':{const grade=gradeQuestion(q,data.session.answers[q.id]);return {title:grade.status==='correct'?'That connection is correct.':grade.status==='needs-review'?'Check this against the rubric.':'A useful place to learn.',subtitle:'STUDY MODE FEEDBACK',body:`<div class="feedback-status ${grade.status}">${icon(grade.status==='correct'?'check':'book')}<span>${statusName(grade.status)}</span></div><div class="answer-comparison"><div><span>Your answer</span><pre>${esc(displayAnswer(q,data.session.answers[q.id]))}</pre></div><div><span>Correct answer</span><pre>${esc(displayAnswer(q,q.correct_answer))}</pre></div></div>${explanationHtml(q)}`,wide:true,footer:'<button class="primary-button" data-action="continue-study">Continue '+icon('arrow')+'</button>'};}
default:return {title:'PacketWise',body:''};}}
function renderModal(){const root=document.querySelector('#modal-root');if(!root)return;document.body.classList.toggle('modal-open',!!ui.modal);document.querySelector('.app-shell')?.toggleAttribute('inert',!!ui.modal);if(!ui.modal){root.innerHTML='';return;}const m=modalContent(ui.modal);root.innerHTML=`<div class="modal-backdrop"><section class="modal ${m.wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header" role="none"><div><span class="eyebrow">${m.subtitle||''}</span><h2 id="modal-title">${m.title}</h2></div><button class="icon-button" data-action="${ui.modal.type==='feedback'?'continue-study':'close-modal'}" aria-label="Close dialog">${icon('close')}</button></header><div class="modal-body">${m.body}</div>${m.footer?`<footer class="modal-footer" role="none">${m.footer}</footer>`:''}</section></div>`;}
function validate(q,response){if(isCli(q))return typeof response==='string'&&response.trim()?'':'Enter your configuration commands, or skip this question.';if(isMatch(q))return Object.keys(q.correct_answer).every(k=>response?.[k])?'':'Choose a match for every item.';if(isOrder(q))return response?.length===q.correct_answer.length&&response.every(Boolean)&&new Set(response).size===q.correct_answer.length?'':'Choose each message exactly once.';if(isMulti(q))return response?.length===q.correct_answer.length?'':`Choose exactly ${q.correct_answer.length} options, or skip this question.`;return response?'':'Choose an answer, or skip this question.';}
function submit(){const q=current();if(!q||data.session.status==='finished')return;const answer=responseFor(q);ui.error=validate(q,answer);if(ui.error){document.querySelector('#answer-error').textContent=ui.error;return;}data.session=recordAnswer(data.session,q,answer);ui.error='';if(data.session.status==='finished')stopTimer();saveAndRender(true);if(data.session.mode==='study')setModal('feedback',{id:q.id});else toast('Answer recorded.');}
function stopTimer(){data.timer.remaining=remaining();data.timer.running=false;data.timer.deadline=null;}
function selectRetest(){const r=resolvedResults();const rank=getStudyPriorities(priorityRows(r)).map(p=>p.domain);const selected=[];for(const domain of rank){for(const q of retestBank.filter(q=>q.domain===domain)){if(selected.length<10&&!selected.includes(q))selected.push(q);}}for(const q of retestBank){if(selected.length>=10)break;if(!selected.includes(q))selected.push(q);}return selected;}
function exportReview(){const r=resolvedResults();const lines=['# PacketWise practice review','',`Score: ${r.score}/${r.total}${r.provisional?' (provisional)':''}`,`Attempted accuracy: ${r.accuracy==null?'N/A':r.accuracy.toFixed(1)+'%'}`,`Correct ${r.correct}; incorrect ${r.incorrect}; skipped ${r.skipped}; unanswered ${r.unanswered}; not presented ${r.unpresented}; awaiting manual CLI review ${r.needsReview}. CLI questions attempted: ${r.cliAttempted}.`,'','## Topic performance',''];for(const t of r.topics)lines.push(`- ${t.topic}: ${t.correct}/${t.attempted} attempted; ${t.accuracy==null?'N/A':t.accuracy.toFixed(1)+'%'}`);for(const [i,row] of r.questions.entries()){const q=row.question;lines.push('',`## Question ${i+1}: ${q.topic} — ${statusName(row.status)}`,'',q.prompt,'',...Object.entries(q.options||{}).map(([k,v])=>`${k}. ${v}`),'',`Your answer: ${displayAnswer(q,row.answer)}`,`Correct answer: ${displayAnswer(q,q.correct_answer)}`,'',q.explanation,...Object.entries(q.distractor_explanations||{}).map(([k,v])=>`${k}: ${v}`),'',...q.source_links);}lines.push('','## Coverage limitations','',...coverageNotes.map(n=>'- '+n));const blob=new Blob([lines.join('\n')],{type:'text/markdown'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`packetwise-${data.kind}-review.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

app.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;event.preventDefault();const action=button.dataset.action;switch(action){
case 'home':ui.mobileOpen=false;render();window.scrollTo({top:0,behavior:'smooth'});break;
case 'menu':ui.mobileOpen=!ui.mobileOpen;render();break;
case 'sources':setModal('sources');break;
case 'guide':setModal('guide');break;
case 'progress':if(data.session.status==='finished'){window.scrollTo({top:0,behavior:'smooth'});}else setModal('progress');break;
case 'mode-exam':data.session={...data.session,mode:'exam'};saveAndRender();toast('Exam mode: feedback appears when you finish.');break;
case 'mode-study':data.session={...data.session,mode:'study'};saveAndRender();toast('Study mode: immediate feedback starts with this question.');break;
case 'timer':if(data.timer.running)stopTimer();else if(remaining()>0){data.timer.deadline=Date.now()+data.timer.remaining*1000;data.timer.running=true;}saveAndRender();break;
case 'flag':{const id=current().id;data.flags=data.flags.includes(id)?data.flags.filter(x=>x!==id):[...data.flags,id];saveAndRender();toast(data.flags.includes(id)?'Flagged. Revisit it from the flagged list.':'Flag removed.');break;}
case 'clarify':setModal('clarify');break;
case 'repeat':closeModal();document.querySelector('#question-title')?.focus();document.querySelector('.question-card')?.scrollIntoView({behavior:'smooth',block:'start'});break;
case 'submit':submit();break;
case 'skip':{const q=current();data.session=skipQuestion(data.session,q);ui.error='';if(data.session.status==='finished')stopTimer();saveAndRender(true);toast('Question skipped.');break;}
case 'view-question':if(Number(button.dataset.id)===current()?.id){closeModal();document.querySelector('#question-title')?.focus();document.querySelector('.question-card')?.scrollIntoView({behavior:'smooth',block:'start'});}else openQuestion(Number(button.dataset.id));break;
case 'return-to-exam':data.session=returnToExam(data.session);ui.error='';saveAndRender(true);break;
case 'review-skipped':setModal('question-list',{filter:'skipped'});break;
case 'review-flags':setModal('question-list',{filter:'flagged'});break;
case 'finish':setModal('finish');break;
case 'confirm-finish':stopTimer();data.session=finishSession(data.session);ui.modal=null;saveAndRender();window.scrollTo(0,0);break;
case 'close-modal':closeModal();break;
case 'continue-study':closeModal();document.querySelector('#question-title')?.focus();break;
case 'download':exportReview();toast('Your review has been exported.');break;
case 'restart':setModal('restart');break;
case 'confirm-restart':stopTimer();replaceAttempt(fresh(false));ui.modal=null;ui.mobileOpen=false;ui.error='';ui.reviewFilter='all';saveAndRender(true);window.scrollTo(0,0);break;
case 'restore':if(data.previousAttempt)setModal('restore');break;
case 'confirm-restore':if(data.previousAttempt){stopTimer();replaceAttempt(data.previousAttempt);ui.modal=null;ui.mobileOpen=false;ui.error='';ui.reviewFilter='all';saveAndRender(true);window.scrollTo(0,0);toast('Previous attempt restored.');}break;
case 'retest':setModal('retest');break;
case 'confirm-retest':{const selected=selectRetest();exportReview();data={...fresh(false),session:createSession(selected,{carryOver:false}),kind:'retest',retestIds:selected.map(q=>q.id),timer:{remaining:1200,running:false,deadline:null}};ui.modal=null;ui.reviewFilter='all';saveAndRender(true);window.scrollTo(0,0);break;}
case 'assess-cli':{const id=Number(button.dataset.id);data.session=reviewAnswer(data.session,questions().find(q=>q.id===id),button.dataset.correct==='true');saveAndRender();toast('Your rubric assessment is recorded.');break;}
}});
app.addEventListener('input',event=>{const el=event.target,q=current();if(!q)return;if(el.dataset.response==='cli'){data.drafts[q.id]=el.value;persist();}});
app.addEventListener('change',event=>{const el=event.target;if(el.id==='review-filter'){ui.reviewFilter=el.value;render();document.querySelector('#review-filter')?.focus();return;}const q=current();if(!q)return;const type=el.dataset.response;if(!type)return;if(type==='choice'){if(isMulti(q)){let chosen=responseFor(q)||[];chosen=el.checked?[...chosen,el.value]:chosen.filter(x=>x!==el.value);data.drafts[q.id]=chosen;}else data.drafts[q.id]=el.value;document.querySelectorAll('.answer-option').forEach(label=>{const checked=label.querySelector('input').checked;label.classList.toggle('selected',checked);label.querySelector('.option-indicator').innerHTML=checked?icon('check'):'';});}if(type==='match')data.drafts[q.id]={...(responseFor(q)||{}),[el.dataset.item]:el.value};if(type==='order'){const arr=[...(responseFor(q)||Array(q.correct_answer.length).fill(''))];arr[Number(el.dataset.item)]=el.value;data.drafts[q.id]=arr;}ui.error='';const err=document.querySelector('#answer-error');if(err)err.textContent='';persist();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&ui.modal){event.preventDefault();closeModal();return;}if(ui.modal&&event.key==='Tab'){const els=[...document.querySelectorAll('.modal a[href], .modal button:not([disabled]), .modal input, .modal select, .modal textarea, .modal summary')].filter(x=>x.getClientRects().length);const first=els[0],last=els.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}return;}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'&&!ui.modal&&data.session.status!=='finished'){event.preventDefault();submit();}});
setInterval(()=>{if(!data.timer.running)return;const time=remaining();const label=document.querySelector('#timer-clock');if(label)label.textContent=timeLabel(time);if(time===0){stopTimer();saveAndRender();toast('Practice time is up. Finish for your review, or keep going at your own pace.');}},1000);
persist();render();
